coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
comment:
  require_changes: false
github_checks:
  annotations: false
