name: ci
on:
  pull_request:
    branches: [ main, feature/*, hotfix/* ]
  push:
    branches: [ main, feature/*, hotfix/* ]
  workflow_dispatch:

env:
  NO_COLOR: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        lfs: true

    - run: dotnet tool install docfx -g

    - uses: ./.github/actions/build

    - run: npm run lint
      shell: bash
      working-directory: templates

    - run: npm test
      shell: bash
      working-directory: templates

    - name: Install `dotnet-coverage` as .NET Global Tool
      run: dotnet tool install -g dotnet-coverage

    - name: Start dotnet-coverage with background server mode
      run: dotnet coverage collect --session-id docfx_coverage --settings test/CodeCoverage.config --server-mode --background

    - run: dotnet coverage connect docfx_coverage "dotnet test -c Release -f net10.0 --no-build"
      id: test-net100

    - name: Upload Logs
      uses: actions/upload-artifact@v7
      if: ${{ !cancelled() }}
      with:
        name: logs-${{ matrix.os }}
        path: |
          msbuild.binlog
          test/**/TestResults/*.log
          test/**/TestResults/*.trx
          test/**/TestResults/*.html
          test/**/TestResults/*.ctrf

    - uses: actions/upload-artifact@v7
      if: ${{ failure() && matrix.os == 'ubuntu-latest' }}
      with:
        name: dump
        path: /tmp/coredump*

