name: ci
on:
  pull_request:
    branches: [ main, feature/*, hotfix/* ]
  push:
    branches: [ main, feature/*, hotfix/* ]
  workflow_dispatch:
    inputs:
      seed:
        description: 'Enter an integer value between 0 and 2147483647.'
        type: number
        required: true
        default: 0

env:
  seed: ${{ inputs.seed || github.run_number }}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        lfs: true

    - uses: ./.github/actions/build

    - run: npm run lint
      shell: bash
      working-directory: templates

    - run: npm test
      shell: bash
      working-directory: templates

    - name: Install Chromium Headless Shell by runnign docfx commands
      run: |
        dotnet run --project src/docfx -c Release --no-build --framework net8.0 --no-launch-profile -- build docs/docfx.json
        dotnet run --project src/docfx -c Release --no-build --framework net8.0 --no-launch-profile -- pdf   docs/docfx.json

    - run: dotnet test -c Release -f net8.0 --no-build --collect:"XPlat Code Coverage" --consoleLoggerParameters:"Summary;Verbosity=Minimal" -- --seed ${{ env.seed }} --no-ansi --no-progress
      id: test-net80

    - run: dotnet test -c Release -f net9.0 --no-build --collect:"XPlat Code Coverage" --consoleLoggerParameters:"Summary;Verbosity=Minimal" -- --seed ${{ env.seed }}
      if: matrix.os == 'ubuntu-latest'
      id: test-net90

    - run: npm i -g @percy/cli
      if: matrix.os == 'ubuntu-latest'

    - run: percy exec -- dotnet test -c Release -f net8.0 --filter Stage=Percy --no-build --collect:"XPlat Code Coverage"
      if: matrix.os == 'ubuntu-latest'
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

    - uses: codecov/codecov-action@v5
      if: matrix.os == 'ubuntu-latest'
      with:
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}

    - run: echo "DOTNET_DbgEnableMiniDump=1" >> $GITHUB_ENV
      if: matrix.os == 'ubuntu-latest'

    - run: dotnet run -c Release --no-build -f net8.0 --project src/docfx -- docs/docfx.json
    - run: dotnet run -c Release --no-build -f net8.0 --project src/docfx -- samples/seed/docfx.json --output docs/_site/seed

    - uses: actions/upload-pages-artifact@v3
      if: matrix.os == 'ubuntu-latest'
      with:
        path: docs/_site

    - name: Upload Logs
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: logs-${{ matrix.os }}
        path: |
          msbuild.binlog
          test/**/TestResults/*.log
          test/**/TestResults/*.trx
          test/**/TestResults/*.html
          test/**/TestResults/*.ctrf

    - uses: actions/upload-artifact@v4
      if: ${{ failure() && matrix.os == 'ubuntu-latest' }}
      with:
        name: dump
        path: /tmp/coredump*

  publish-docs:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [test]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      pages: write
      id-token: write
    steps:
    - id: deployment
      uses: actions/deploy-pages@v4
