name: lint

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false   
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.x

      - name: Run `dotnet restore` command
        run: |
          dotnet restore

      - name: Run `dotnet format` command
        run: | 
          dotnet format whitespace --no-restore --verify-no-changes
          dotnet format style      --no-restore --verify-no-changes
          dotnet format analyzers  --no-restore --verify-no-changes

      - name: Add comment to Pull Request
        if: ${{ failure() && github.event_name == 'pull_request' }}
        shell: pwsh
        run: |
          $content = '
          ## Diffs are detected
          Run the following commands on the local environment. And commit changes as separated commit.
           - `dotnet format whitespace`
           - `dotnet format style`
           - `dotnet format analyzers`
          '
          gh pr comment ${{ github.event.number }} --body "$content" --edit-last || gh pr comment ${{ github.event.number }} --body "$content"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
