name: lint

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false   
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.x

      - name: Run `dotnet restore` command
        run: |
          dotnet restore

      - name: Run `dotnet format` command
        run: | 
          dotnet format whitespace --no-restore --verify-no-changes
          dotnet format style      --no-restore --verify-no-changes
          dotnet format analyzers  --no-restore --verify-no-changes

      - name: Report failures
        if: ${{ failure() }}
        shell: pwsh
        run: |
          $content = '
          ## Failed to run `dotnet format --verify-no-changes`
          Diffs are detected when running `dotnet format` commands on CI.
          Run the following commands on the local environment and commit changes as separated commit.

          ```
          dotnet format whitespace
          dotnet format style
          dotnet format analyzers
          ```
          '
          Write-Output $content >> $env:GITHUB_STEP_SUMMARY

      - name: Add comment to Pull Request
        if: ${{ failure() && github.event_name == 'pull_request' }}
        shell: pwsh
        run: |
          Write-Host $env:GITHUB_STEP_SUMMARY
          $content = Get-Content $env:GITHUB_STEP_SUMMARY -Raw
          gh pr comment ${{ github.event.number }} --body $content --edit-last || gh pr comment ${{ github.event.number }} --body $content
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
