name: nightly2
on:
  push:
  workflow_dispatch:

env:
  DOCFX_PREVIEW_BUILD: false

jobs:
  publish-github-packages:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
 
    - id: version
      uses: paulhatch/semantic-version@v5.4.0
      with:
        version_format: ${major}.${minor}.${patch}-preview.${increment}

    # - uses: ./.github/actions/build

    - run: dir /home/runner/work/docfx/docfx/src/Docfx.App/Build
   
    - name: dotnet pack
      run: |
        cd src/Docfx.App/
        dotnet pack -c Release /p:Version=${{ steps.version.outputs.version }} /p:ApiCompatGenerateSuppressionFile=true -o drop/nuget

    - uses: actions/upload-artifact@v4
      with:
        name: nupkg
        path: drop/nuget/*

